# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /root/COD_Lab/Lab4/lab4_files/lab4_files/PDU_src/约束/constrains.xdc

# IP: ip/DATA_MEM/DATA_MEM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DATA_MEM || ORIG_REF_NAME==DATA_MEM} -quiet] -quiet

# IP: ip/INST_MEM/INST_MEM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INST_MEM || ORIG_REF_NAME==INST_MEM} -quiet] -quiet
