# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /root/COD_Lab/Lab6/Lab6/Lab6.srcs/sources_1/ip/main_memory/main_memory.xci
# IP: The module: 'main_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /root/COD_Lab/Lab6/Lab6/Lab6.srcs/sources_1/ip/main_memory/main_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /root/COD_Lab/Lab6/Lab6/Lab6.srcs/sources_1/ip/main_memory/main_memory.xci
# IP: The module: 'main_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /root/COD_Lab/Lab6/Lab6/Lab6.srcs/sources_1/ip/main_memory/main_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
