# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /root/COD_Lab/Lab5/Lab5/Lab5.srcs/sources_1/ip/INST_MEM/INST_MEM.xci
# IP: The module: 'INST_MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /root/COD_Lab/Lab5/Lab5/Lab5.srcs/sources_1/ip/INST_MEM/INST_MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INST_MEM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /root/COD_Lab/Lab5/Lab5/Lab5.srcs/sources_1/ip/INST_MEM/INST_MEM.xci
# IP: The module: 'INST_MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /root/COD_Lab/Lab5/Lab5/Lab5.srcs/sources_1/ip/INST_MEM/INST_MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INST_MEM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
