# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/expecto/Desktop/COD_Lab/Lab2/Lab2.srcs/sources_1/ip/blk_write_first/blk_write_first.xci
# IP: The module: 'blk_write_first' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/expecto/Desktop/COD_Lab/Lab2/Lab2.srcs/sources_1/ip/blk_write_first/blk_write_first_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_write_first'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/expecto/Desktop/COD_Lab/Lab2/Lab2.srcs/sources_1/ip/blk_write_first/blk_write_first.xci
# IP: The module: 'blk_write_first' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/expecto/Desktop/COD_Lab/Lab2/Lab2.srcs/sources_1/ip/blk_write_first/blk_write_first_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_write_first'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
