# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-17322-VM5818-Ubuntu/incrSyn
set_param chipscope.maxJobs 2
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /root/COD_Lab/Lab6_pipeline/Lab6/Lab6.cache/wt [current_project]
set_property parent.project_path /root/COD_Lab/Lab6_pipeline/Lab6/Lab6.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /root/COD_Lab/Lab6_pipeline/Lab6/Lab6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /root/COD_Lab/Lab6_pipeline/testbench/qsort.coe
read_verilog -library xil_defaultlib {
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/ADDER_PC.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/ALU.v
  /root/COD_Lab/Lab6_pipeline/modules/cache/BRAM.v
  /root/COD_Lab/Lab6_pipeline/modules/cache/BRAM_common.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/Branch.v
  /root/COD_Lab/Lab6_pipeline/modules/CPU.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/CTRL.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/Hazard.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/IMM.v
  /root/COD_Lab/Lab6_pipeline/modules/MEM.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/MUX.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/MUX_PC.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/MUX_RFwrite.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/PC.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/PC_pre.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/RF.v
  /root/COD_Lab/Lab6_pipeline/modules/pipeline/CPU_core/SEG_REG.v
  /root/COD_Lab/Lab6_pipeline/modules/cache/axi_arbiter.v
  /root/COD_Lab/Lab6_pipeline/modules/cache/dcache.v
  /root/COD_Lab/Lab6_pipeline/modules/cache/icache.v
  /root/COD_Lab/Lab6_pipeline/modules/Top.v
}
read_ip -quiet /root/COD_Lab/Lab6_pipeline/Lab6/Lab6.srcs/sources_1/ip/main_memory/main_memory.xci
set_property used_in_implementation false [get_files -all /root/COD_Lab/Lab6_pipeline/Lab6/Lab6.srcs/sources_1/ip/main_memory/main_memory_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /root/COD_Lab/Lab6_pipeline/constraints/constrains.xdc
set_property used_in_implementation false [get_files /root/COD_Lab/Lab6_pipeline/constraints/constrains.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
