# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/expecto/Desktop/COD_Lab/Lab2/Lab2.srcs/sources_1/ip/blk_default/blk_default.xci
# IP: The module: 'blk_default' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/expecto/Desktop/COD_Lab/Lab2/Lab2.srcs/sources_1/ip/blk_default/blk_default_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_default'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/expecto/Desktop/COD_Lab/Lab2/Lab2.srcs/sources_1/ip/blk_default/blk_default.xci
# IP: The module: 'blk_default' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/expecto/Desktop/COD_Lab/Lab2/Lab2.srcs/sources_1/ip/blk_default/blk_default_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_default'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
